// Exact compiled component metadata; references belong to modules/44785.js
({
  type: Uh,
  selectors: [["app-pillbox-label-print"]],
  decls: 25,
  vars: 15,
  consts: [[1, "barcode-label-modal"], [1, "modal-header"], [1, "modal-title"], ["lu-button-icon", "", 1, "close-btn", 3, "click"], ["icon", "close", 3, "size"], [1, "modal-body"], [1, "barcode-wrapper"], [3, "bc-height", "bc-width", "bc-value", "bc-format", "bc-display-value"], [1, "barcode-number"], [1, "patient-name"], [1, "patient-info"], [1, "dot"], ["class", "error-message", 4, "ngIf"], [1, "modal-footer"], ["lu-button-raised", "", 3, "color", "disabled", "click"], ["icon", "print", 3, "size"], [1, "error-message"]],
  template: function (k, ce) {
    1 & k && (n.TgZ(0, "div", 0)(1, "div", 1)(2, "h2", 2), n._uU(3, "Печать этикетки для таблетницы"), n.qZA(), n.TgZ(4, "button", 3), n.NdJ("click", function () {
      return ce.close();
    }), n._UZ(5, "lu-svg-icon", 4), n.qZA()(), n.TgZ(6, "div", 5)(7, "div", 6), n._UZ(8, "ngx-barcode6", 7), n.qZA(), n.TgZ(9, "div", 8), n._uU(10), n.qZA(), n.TgZ(11, "div", 9), n._uU(12), n.qZA(), n.TgZ(13, "div", 10)(14, "span"), n._uU(15), n.qZA(), n.TgZ(16, "span", 11), n._uU(17, "•"), n.qZA(), n.TgZ(18, "span"), n._uU(19), n.qZA()(), n.YNc(20, Ri, 2, 1, "div", 12), n.qZA(), n.TgZ(21, "div", 13)(22, "button", 14), n.NdJ("click", function () {
      return ce.printLabel();
    }), n._UZ(23, "lu-svg-icon", 15), n._uU(24), n.qZA()()()), 2 & k && (n.xp6(5), n.Q6J("size", 24), n.xp6(3), n.Q6J("bc-height", 80)("bc-width", 2)("bc-value", ce.data.barcode)("bc-format", "CODE128")("bc-display-value", !1), n.xp6(2), n.Oqu(ce.data.barcode), n.xp6(2), n.Oqu(ce.formattedFio), n.xp6(3), n.Oqu(ce.data.card), n.xp6(4), n.hij("Палата №", ce.data.room, ""), n.xp6(1), n.Q6J("ngIf", ce.errorMessage), n.xp6(2), n.Q6J("color", "blue")("disabled", ce.isPrinting), n.xp6(1), n.Q6J("size", 16), n.xp6(1), n.hij(" ", ce.isPrinting ? "Печать..." : "Распечатать", " "));
  },
  dependencies: [Di.O5, Ks.mc, Ro.k, Ci.q, qs.y],
  styles: [".barcode-label-modal[_ngcontent-%COMP%]{width:448px;background:#fff;border-radius:8px;box-shadow:0 10px 32px #161a3c1c;display:flex;flex-direction:column}.modal-header[_ngcontent-%COMP%]{display:flex;justify-content:space-between;align-items:flex-start;padding:24px 24px 0}.modal-title[_ngcontent-%COMP%]{font-family:Open Sans,sans-serif;font-size:20px;font-weight:600;line-height:28px;color:#23282c;margin:0}.close-btn[_ngcontent-%COMP%]{flex-shrink:0;margin-left:16px}.modal-body[_ngcontent-%COMP%]{display:flex;flex-direction:column;align-items:center;padding:24px}.barcode-wrapper[_ngcontent-%COMP%]{display:flex;justify-content:center;align-items:center;margin-bottom:4px}.barcode-wrapper[_ngcontent-%COMP%]   ngx-barcode6[_ngcontent-%COMP%]{display:block}.barcode-wrapper[_ngcontent-%COMP%]   ngx-barcode6[_ngcontent-%COMP%]     svg{width:100%;max-width:400px;height:auto}.barcode-number[_ngcontent-%COMP%]{font-family:Open Sans,sans-serif;font-size:18px;font-weight:400;line-height:24px;color:#23282c;text-align:center;margin-bottom:24px}.patient-name[_ngcontent-%COMP%]{font-family:Open Sans,sans-serif;font-size:15px;font-weight:400;line-height:24px;color:#23282c;text-align:center;margin-bottom:4px}.patient-info[_ngcontent-%COMP%]{display:flex;align-items:center;justify-content:center;flex-wrap:wrap;gap:4px 8px;font-family:Open Sans,sans-serif;font-size:15px;font-weight:400;line-height:24px;color:#757575;text-align:center}.dot[_ngcontent-%COMP%]{color:#bdbdbd}.error-message[_ngcontent-%COMP%]{margin-top:16px;padding:12px 16px;background:#FFF3F3;border:1px solid #FFCDD2;border-radius:4px;color:#d32f2f;font-family:Open Sans,sans-serif;font-size:14px;line-height:20px;text-align:center;width:100%}.modal-footer[_ngcontent-%COMP%]{display:flex;justify-content:flex-end;padding:0 24px 24px}"],
  changeDetection: 0
});
