// Exact compiled component metadata; references belong to modules/44785.js
({
  type: bd,
  selectors: [["app-injections-label-print"]],
  decls: 39,
  vars: 17,
  consts: [[3, "title"], [1, "qr-wrapper"], [3, "qrdata", "width"], [1, "patient-info"], [1, "patient-info__fio"], [1, "patient-info__details"], [1, "dot"], [4, "ngIf"], [1, "medicine"], ["class", "medicine__row", 4, "ngFor", "ngForOf"], [1, "sep"], [1, "medicine__info"], [1, "medicine__info__row"], ["lu-text", "", "color", "muted"], [1, "qr-footer"], ["lu-button-raised", "", 3, "size", "color", "click"], ["icon", "print", 3, "size"], [1, "medicine__row"], [1, "medicine__row__name"], [1, "medicine__row__dose"]],
  template: function (k, ce) {
    1 & k && (n.TgZ(0, "common-modal-wrapper", 0)(1, "div", 1), n._UZ(2, "qrcode", 2), n.TgZ(3, "div", 3)(4, "div", 4), n._uU(5), n.qZA(), n.TgZ(6, "div"), n._uU(7), n.qZA(), n.TgZ(8, "div", 5)(9, "span"), n._uU(10), n.qZA(), n._UZ(11, "span", 6), n.TgZ(12, "span"), n._uU(13), n.qZA(), n.YNc(14, Tl, 4, 1, "ng-container", 7), n.qZA()()(), n.TgZ(15, "div", 8), n.YNc(16, $c, 5, 2, "div", 9), n._UZ(17, "div", 10), n.TgZ(18, "div", 11)(19, "div", 12)(20, "span", 13), n._uU(21, "Способ введения:\xA0"), n.qZA(), n.TgZ(22, "span"), n._uU(23), n.qZA()(), n.TgZ(24, "div", 12)(25, "span", 13), n._uU(26, "Длительность:\xA0"), n.qZA(), n.TgZ(27, "span"), n._uU(28), n.qZA()(), n.TgZ(29, "div", 12)(30, "span", 13), n._uU(31, "Примечание:\xA0"), n.qZA(), n.TgZ(32, "span"), n._uU(33), n.qZA(), n._UZ(34, "span"), n.qZA()()(), n.TgZ(35, "div", 14)(36, "button", 15), n.NdJ("click", function () {
      return ce.printLabel();
    }), n._UZ(37, "lu-svg-icon", 16), n._uU(38, " Распечатать "), n.qZA()()()), 2 & k && (n.Q6J("title", "Печать маркировки на назначение"), n.xp6(2), n.Q6J("qrdata", ce.data.medicine[0].code)("width", 147), n.xp6(3), n.Oqu(ce.modalData.patientFio), n.xp6(2), n.AsE("", ce.modalData.age, " лет, ", ce.modalData.birthday, ""), n.xp6(3), n.Oqu(ce.modalData.medCardNumber), n.xp6(3), n.Oqu(ce.modalData.ward), n.xp6(1), n.Q6J("ngIf", ce.modalData.bed), n.xp6(2), n.Q6J("ngForOf", ce.data.medicine), n.xp6(7), n.AsE("", ce.data.medicine[0].method, ", ", ce.data.medicine[0].frequency, ""), n.xp6(5), n.Oqu(ce.getInjectionDuration(null == ce.data || null == ce.data.medicine[0] ? null : ce.data.medicine[0].durationInjectionSpeed)), n.xp6(5), n.Oqu(ce.data.medicine[0].comment), n.xp6(3), n.Q6J("size", "medium")("color", "blue"), n.xp6(1), n.Q6J("size", 16));
  },
  dependencies: [Di.sg, Di.O5, hc, Hc.$, Ks.mc, Ci.q, Kt.NZ],
  styles: [".qr-wrapper[_ngcontent-%COMP%]{display:flex;align-items:flex-start;gap:5px;margin-bottom:8px}.qr-wrapper[_ngcontent-%COMP%]   qrcode[_ngcontent-%COMP%]{margin-left:-16px;margin-top:-16px}.qr-wrapper[_ngcontent-%COMP%]   qrcode[_ngcontent-%COMP%]     .qrcode{display:flex}.patient-info[_ngcontent-%COMP%]{display:flex;flex-direction:column;gap:4px;font-size:13px;line-height:1.539}.patient-info__fio[_ngcontent-%COMP%]{font-size:15px;font-weight:600;line-height:1.6}.patient-info__details[_ngcontent-%COMP%]{display:flex;align-items:center;gap:8px}.medicine[_ngcontent-%COMP%]{padding:16px;background-color:#f2f2f2;border-radius:4px;display:flex;flex-direction:column;gap:8px}.medicine__row[_ngcontent-%COMP%]{display:flex;flex-direction:column}.medicine__row__name[_ngcontent-%COMP%]{font-weight:600}.medicine__row__dose[_ngcontent-%COMP%]{font-size:13px;color:#757575;line-height:1.539}.medicine__info[_ngcontent-%COMP%]{display:flex;flex-direction:column;gap:2px}.medicine__info__row[_ngcontent-%COMP%]{display:flex;flex-direction:row}.medicine[_ngcontent-%COMP%]   .sep[_ngcontent-%COMP%]{margin:12px 0;border-top:1px solid #e6e6e6}.qr-footer[_ngcontent-%COMP%]{margin-top:16px;text-align:right}.qr-footer[_ngcontent-%COMP%]     .lu-button-wrapper .lu-button-content:first-child{display:none}"],
  changeDetection: 0
});
