// Exact compiled component metadata; references belong to modules/19339.js
({
  type: B,
  selectors: [["app-complete-form"]],
  standalone: !0,
  features: [e.jDz],
  decls: 10,
  vars: 4,
  consts: [["class", "loader-wrapper", 4, "ngIf"], [1, "complete-form"], [1, "complete-form__header"], ["lu-button-icon", "", 3, "click"], ["icon", "close", 1, "icon-close", 3, "size"], [4, "ngIf", "ngIfElse"], ["content", ""], [1, "loader-wrapper"], [1, "loader"], [1, "complete-form__loader"], [1, "complete-form__content"], [1, "complete-form__content__title"], [1, "bold_span"], [1, "complete-form__content__description"], [1, "complete-form__actions"], ["lu-button-outer", "", 1, "complete-form__actions__button", 3, "disabled", "click"], ["lu-button-raised", "", 1, "complete-form__actions__button", 3, "disabled", "click"], ["icon", "check-mse", 3, "size"]],
  template: function (W, F) {
    if (1 & W && (e.YNc(0, x, 2, 0, "div", 0), e.TgZ(1, "div", 1)(2, "div", 2)(3, "span"), e._uU(4, "Выполнение процедуры или манипуляции"), e.qZA(), e.TgZ(5, "button", 3), e.NdJ("click", function () {
      return F.onClose();
    }), e._UZ(6, "lu-svg-icon", 4), e.qZA()(), e.YNc(7, u, 3, 0, "ng-container", 5), e.YNc(8, T, 19, 5, "ng-template", null, 6, e.W1O), e.qZA()), 2 & W) {
      const Le = e.MAs(9);
      e.Q6J("ngIf", F.isLoad), e.xp6(6), e.Q6J("size", 24), e.xp6(1), e.Q6J("ngIf", F.isLoading)("ngIfElse", Le);
    }
  },
  dependencies: [N.ez, N.O5, m.W1, m.mc, d.h, d.q, M.o, M.k, b.aI, A.c, A.d],
  styles: [".complete-form[_ngcontent-%COMP%]{padding:24px}.complete-form__header[_ngcontent-%COMP%]{display:flex;flex-direction:row;justify-content:space-between;align-items:flex-start}.complete-form__header[_ngcontent-%COMP%]   span[_ngcontent-%COMP%]{font-weight:600;font-size:20px;line-height:28px}.complete-form__header[_ngcontent-%COMP%]     .lu-button-wrapper{align-items:flex-start}.complete-form__header[_ngcontent-%COMP%]     .lu-button-wrapper .lu-button-icon{width:auto;height:auto}.complete-form__loader[_ngcontent-%COMP%]{display:flex;align-items:center;justify-content:center;width:100%;flex:1}  .complete-form__header .lu-button-icon{--lu-button-hover-text: #CCCCCC !important;--lu-svg-icon-color: #CCCCCC !important}  .complete-form__header .lu-button-icon:hover{--lu-svg-icon-color: #999999 !important;cursor:pointer}.complete-form__content[_ngcontent-%COMP%]{margin-top:24px;display:flex;flex-direction:column;gap:16px}.complete-form__content__title[_ngcontent-%COMP%]{line-height:24px}.complete-form__content__title[_ngcontent-%COMP%]   .bold_span[_ngcontent-%COMP%]{font-weight:600}.complete-form__content__title[_ngcontent-%COMP%]   p[_ngcontent-%COMP%]{margin:0}.complete-form__actions[_ngcontent-%COMP%]{margin-top:32px;display:flex;flex-direction:row;justify-content:end;gap:16px}.complete-form__actions[_ngcontent-%COMP%]     button[lu-button-outer], .complete-form__actions[_ngcontent-%COMP%]     button[lu-button-raised]{height:40px}.complete-form__actions[_ngcontent-%COMP%]     button[lu-button-outer] .lu-button-wrapper, .complete-form__actions[_ngcontent-%COMP%]     button[lu-button-raised] .lu-button-wrapper{height:40px!important;padding:8px 16px!important;line-height:24px!important}.complete-form__actions[_ngcontent-%COMP%]     button[lu-button-outer] .lu-button-wrapper .lu-button-content, .complete-form__actions[_ngcontent-%COMP%]     button[lu-button-raised] .lu-button-wrapper .lu-button-content{display:none}.complete-form__actions[_ngcontent-%COMP%]     button[lu-button-outer] .lu-button-wrapper .lu-button-text, .complete-form__actions[_ngcontent-%COMP%]     button[lu-button-raised] .lu-button-wrapper .lu-button-text{font-weight:600;font-size:16px}.complete-form__actions[_ngcontent-%COMP%]     button[lu-button-outer]{width:114px}.complete-form__actions[_ngcontent-%COMP%]     button[lu-button-raised]{width:149px}.loader-wrapper[_ngcontent-%COMP%]{position:absolute;top:0;left:0;display:flex;align-items:center;justify-content:center;width:100%;height:100%;background-color:rgba(var(--lu-black-rgb-100),.5);z-index:100}.loader[_ngcontent-%COMP%]{width:48px;height:48px;border:5px solid #fff;border-bottom-color:transparent;border-radius:50%;display:inline-block;box-sizing:border-box;animation:_ngcontent-%COMP%_rotation 1s linear infinite}@keyframes _ngcontent-%COMP%_rotation{0%{transform:rotate(0)}to{transform:rotate(360deg)}}"]
});
