// Exact compiled component metadata; references belong to modules/15513.js
({
  type: Q_,
  selectors: [["app-place-patient-modal"]],
  viewQuery: function (o, D) {
    if (1 & o && e.Gf(p2, 5), 2 & o) {
      let Z;
      e.iGM(Z = e.CRH()) && (D.modalRef = Z.first);
    }
  },
  decls: 53,
  vars: 30,
  consts: [[3, "title"], ["modalRef", ""], [1, "place-patient"], ["class", "place-patient__item", 4, "ngIf"], [3, "formGroup"], [1, "place-patient__content"], [1, "place-patient__item", "place-patient__item-width"], [1, "form__group-label"], ["lu-label", ""], ["type", "autocomplete", "formControlName", "ward", 3, "ngClass", "displayValueFn", "beforeOpen"], ["combobox", ""], [3, "items", "itemContent", "showPreloader", 4, "luData"], ["type", "error", 4, "ngIf"], [1, "place-patient__item__group"], [1, "place-patient__item--ward"], [1, "place-patient__item-width"], ["type", "autocomplete", "formControlName", "bedProfile", 3, "ngClass", "displayValueFn"], ["comboboxBed", ""], [1, "place-patient__bed-item-width"], ["luInput", "", "luInputString", "", "formControlName", "bed", 1, "no-focus"], [1, "place-patient__item"], ["type", "autocomplete", "formControlName", "doctor", 3, "ngClass", "displayValueFn"], [3, "ngModel", "checked", "ngModelOptions", "ngModelChange"], ["lu-label", "Фактическое размещение", 4, "ngIf"], [1, "place-patient__footer"], ["lu-button-raised", "", 2, "margin-top", "16px", 3, "size", "color", "isLoading", "disabled", "click"], [1, "place-patient__item-title"], [3, "items", "itemContent", "showPreloader"], ["itemContent", ""], [3, "innerHTML"], ["type", "error"], ["icon", "warning", 3, "size"], ["lu-text", "", 3, "innerHTML"], ["lu-text", "", 1, "info-label"], ["lu-label", "Фактическое размещение"], ["luInput", "", "luInputString", "", "formControlName", "actualPlacement"]],
  template: function (o, D) {
    if (1 & o && (e.TgZ(0, "common-modal-wrapper", 0, 1)(2, "div", 2), e.YNc(3, JM, 5, 1, "div", 3), e.YNc(4, QM, 5, 1, "div", 3), e.YNc(5, ED, 5, 1, "div", 3), e.TgZ(6, "form", 4)(7, "div", 5)(8, "div", 6)(9, "span", 7), e._uU(10, "Палата "), e.TgZ(11, "span"), e._uU(12, "*"), e.qZA()(), e.TgZ(13, "label", 8)(14, "lu-combobox", 9, 10), e.NdJ("beforeOpen", function () {
      return D.onOpenWards();
    }), e.YNc(16, DD, 4, 6, "lu-data-list", 11), e.qZA(), e.YNc(17, PD, 3, 1, "lu-form-message", 12), e.qZA()(), e.TgZ(18, "div", 13)(19, "div", 14)(20, "div", 15)(21, "span", 7), e._uU(22, "Профиль койки "), e.TgZ(23, "span"), e._uU(24, "*"), e.qZA()(), e.TgZ(25, "label", 8)(26, "lu-combobox", 16, 17), e.YNc(28, XM, 4, 6, "lu-data-list", 11), e.qZA(), e.YNc(29, AD, 3, 1, "lu-form-message", 12), e.qZA()(), e.TgZ(30, "div", 18)(31, "span", 7), e._uU(32, "Койка"), e.qZA(), e.TgZ(33, "label", 8)(34, "lu-input-wrapper"), e._UZ(35, "input", 19), e.qZA()()()()(), e.TgZ(36, "div", 20)(37, "span", 7), e._uU(38, "Лечащий врач "), e.TgZ(39, "span"), e._uU(40, "*"), e.qZA()(), e.TgZ(41, "label", 8)(42, "lu-combobox", 21, 10), e.YNc(44, ID, 4, 6, "lu-data-list", 11), e.qZA(), e.YNc(45, LD, 3, 1, "lu-form-message", 12), e.qZA()(), e.TgZ(46, "div")(47, "lu-checkbox", 22), e.NdJ("ngModelChange", function (X) {
      return D.isFactPlacementMatch = X;
    })("ngModelChange", function () {
      return D.changePlacement();
    }), e._uU(48, " Совпадает с фактическим размещением "), e.qZA()(), e.YNc(49, wC, 3, 0, "label", 23), e.qZA(), e.TgZ(50, "div", 24)(51, "button", 25), e.NdJ("click", function () {
      return D.onSubmit();
    }), e._uU(52), e.qZA()()()()()), 2 & o) {
      let Z, X, oe;
      e.Q6J("title", D.title), e.xp6(3), e.Q6J("ngIf", D.getDepartment), e.xp6(1), e.Q6J("ngIf", D.getPlacementDate), e.xp6(1), e.Q6J("ngIf", D.getActualDiagnoses), e.xp6(1), e.Q6J("formGroup", D.placementForm), e.xp6(8), e.Q6J("ngClass", e.VKq(23, f2, D.isTablet))("displayValueFn", D.displayWardFn), e.xp6(3), e.Q6J("ngIf", (null == (Z = D.placementForm.get("ward")) ? null : Z.hasError("required")) && (null == (Z = D.placementForm.get("ward")) ? null : Z.touched)), e.xp6(9), e.Q6J("ngClass", e.VKq(25, f2, D.isTablet))("displayValueFn", D.displayBedProfileFn), e.xp6(3), e.Q6J("ngIf", (null == (X = D.placementForm.get("bedProfile")) ? null : X.hasError("required")) && (null == (X = D.placementForm.get("bedProfile")) ? null : X.touched)), e.xp6(13), e.Q6J("ngClass", e.VKq(27, f2, D.isTablet))("displayValueFn", D.displayDoctorFn), e.xp6(3), e.Q6J("ngIf", (null == (oe = D.placementForm.get("doctor")) ? null : oe.hasError("required")) && (null == (oe = D.placementForm.get("doctor")) ? null : oe.touched)), e.xp6(2), e.Q6J("ngModel", D.isFactPlacementMatch)("checked", D.isFactPlacementMatch)("ngModelOptions", e.DdM(29, m2)), e.xp6(2), e.Q6J("ngIf", !D.isFactPlacementMatch), e.xp6(2), e.Q6J("size", "medium")("color", "blue")("isLoading", D.isLoading)("disabled", D.isLoading), e.xp6(1), e.hij(" ", D.modalState.buttonText, " ");
    }
  },
  dependencies: [vo.mk, vo.O5, pr._Y, pr.Fj, pr.JJ, pr.JL, pr.On, pr.sg, pr.u, ih.z, Km.m, ef.l, Cm.g, oh.l, Oa.q, Xl.mc, ym.$m, Ju.HY, id.L, pp.H, H4.$, o_.J, bg.e],
  styles: ["@charset \"UTF-8\";  .cdk-global-overlay-wrapper:has(.place-patient-modal){position:relative;top:6px}.place-patient[_ngcontent-%COMP%]{display:flex;flex-direction:column;gap:24px;width:528px}@media (min-width: 600px) and (max-width: 960px){.place-patient[_ngcontent-%COMP%]{width:100%;height:calc(100vh - 96px)}}.place-patient[_ngcontent-%COMP%]   form[_ngcontent-%COMP%]{display:flex;flex-direction:column;justify-content:space-between;flex-grow:1;gap:24px}.place-patient__content[_ngcontent-%COMP%]{display:flex;gap:24px;flex-direction:column;height:100%}.place-patient__bed-item-width[_ngcontent-%COMP%]{width:calc(100% - 348px)}.place-patient__item-width[_ngcontent-%COMP%]{width:332px}.place-patient__item__group[_ngcontent-%COMP%]{display:flex;flex-direction:row;gap:16px}.place-patient__item__group[_ngcontent-%COMP%]   .place-patient__item[_ngcontent-%COMP%]{width:100%}.place-patient__item__group[_ngcontent-%COMP%]   .place-patient__item[_ngcontent-%COMP%]   .info-label[_ngcontent-%COMP%]{color:var(--lu-black-54)}.place-patient__item-title[_ngcontent-%COMP%]{color:#757575;margin-bottom:4px}.place-patient__item--ward[_ngcontent-%COMP%]{display:flex;gap:16px}.place-patient__footer[_ngcontent-%COMP%]{text-align:right;margin-top:-18px}@media (min-width: 600px) and (max-width: 960px){.place-patient__footer[_ngcontent-%COMP%]{width:calc(100vw - 1px);border-top:1px solid #e6e6e6;margin:0 -16px;padding-right:16px}}[_nghost-%COMP%]     .border-combobox [data-lu-focused=true]:not(:focus-within){--lu-floated-border: transparent !important}[_nghost-%COMP%]     .border-combobox [data-lu-focused=true]:not(:focus-within), [_nghost-%COMP%]     .border-combobox [data-lu-focused=true]:not(:focus-within) *, [_nghost-%COMP%]     .border-combobox [data-lu-focused=true]:not(:focus-within) div, [_nghost-%COMP%]     .border-combobox [data-lu-focused=true]:not(:focus-within) input{box-shadow:none!important}[_nghost-%COMP%]     .border-combobox [data-lu-focused=true]:not(:focus-within) .lu-input, [_nghost-%COMP%]     .border-combobox [data-lu-focused=true]:not(:focus-within) .main-container, [_nghost-%COMP%]     .border-combobox [data-lu-focused=true]:not(:focus-within) .combobox-wrapper{border:1px solid #FFFFFF!important}"]
});
