// Exact compiled component metadata; references belong to modules/79327.js
({
  type: Di,
  selectors: [["app-add-patient-modal"]],
  decls: 48,
  vars: 18,
  consts: [[3, "title"], [1, "form", "add-patient"], [1, "form__group", "form__group--dept"], ["lu-label", "Отделение"], ["type", "autocomplete", 3, "formControl"], ["comboboxDept", ""], [3, "items", "itemContent", "displayValueFn", 4, "luData"], [1, "form__group"], [1, "form__group-label"], ["lu-label", ""], ["type", "autocomplete", 3, "clearButton", "formControl"], ["comboboxFio", ""], ["type", "error", 4, "ngIf"], [1, "wrap"], [1, "date"], [3, "formControl", "minDate", "maxDate"], [1, "time"], ["type", "text", "luInput", "", "luInputString", "", "luMask", "HH:MM", "placeholder", "ЧЧ:ММ", "autocomplete", "off", 3, "formControl"], [1, "tube"], ["comboboxSize", ""], [3, "items", "itemContent", 4, "luData"], [1, "btn-wrapper"], ["lu-button-raised", "", 3, "size", "color", "click"], [4, "ngIf"], [3, "items", "itemContent", "displayValueFn"], ["deptTemplate", ""], [3, "innerHTML"], ["patientTemplate", ""], ["type", "error"], ["icon", "warning", 3, "size"], [3, "items", "itemContent"], ["tubeTemplate", ""]],
  template: function (Rn, ki) {
    1 & Rn && (d.TgZ(0, "common-modal-wrapper", 0)(1, "form", 1)(2, "div", 2)(3, "label", 3)(4, "lu-combobox", 4, 5), d.YNc(6, Ct, 4, 6, "lu-data-list", 6), d.qZA()()(), d.TgZ(7, "div", 7)(8, "span", 8), d._uU(9, "ФИО пациента "), d.TgZ(10, "span"), d._uU(11, "*"), d.qZA()(), d.TgZ(12, "label", 9)(13, "lu-combobox", 10, 11), d.YNc(15, Et, 4, 6, "lu-data-list", 6), d.qZA(), d.YNc(16, Ue, 3, 1, "lu-form-message", 12), d.qZA()(), d.TgZ(17, "div", 13)(18, "div", 14)(19, "span", 8), d._uU(20, "Дата установки "), d.TgZ(21, "span"), d._uU(22, "*"), d.qZA()(), d.TgZ(23, "label", 9), d._UZ(24, "lu-calendar-field", 15), d.YNc(25, Me, 3, 1, "lu-form-message", 12), d.qZA()(), d.TgZ(26, "div", 16)(27, "span", 8), d._uU(28, "Время"), d.qZA(), d.TgZ(29, "label", 9)(30, "lu-input-wrapper"), d._UZ(31, "input", 17), d.YNc(32, Ke, 3, 1, "lu-form-message", 12), d.YNc(33, Ze, 3, 1, "lu-form-message", 12), d.qZA()()(), d.TgZ(34, "div", 18)(35, "span", 8), d._uU(36, "Размер зонда "), d.TgZ(37, "span"), d._uU(38, "*"), d.qZA()(), d.TgZ(39, "label", 9)(40, "lu-combobox", 10, 19), d.YNc(42, je, 4, 5, "lu-data-list", 20), d.qZA(), d.YNc(43, Mt, 3, 1, "lu-form-message", 12), d.qZA()()(), d.TgZ(44, "div", 21)(45, "button", 22), d.NdJ("click", function () {
      return ki.onSubmit();
    }), d._uU(46, "Добавить"), d.qZA()()()(), d.YNc(47, Je, 1, 0, "app-loader", 23)), 2 & Rn && (d.Q6J("title", "Добавление нового пациента"), d.xp6(4), d.Q6J("formControl", ki.deptControl), d.xp6(9), d.Q6J("clearButton", !1)("formControl", ki.patientControl), d.xp6(3), d.Q6J("ngIf", ki.patientControl.hasError("required")), d.xp6(8), d.Q6J("formControl", ki.dateControl)("minDate", ki.minDate)("maxDate", ki.maxDate), d.xp6(1), d.Q6J("ngIf", ki.dateControl.hasError("required")), d.xp6(6), d.Q6J("formControl", ki.timeControl), d.xp6(1), d.Q6J("ngIf", ki.timeControl.touched && ki.timeControl.hasError("invalidTime")), d.xp6(1), d.Q6J("ngIf", ki.timeControl.touched && ki.timeControl.hasError("required")), d.xp6(7), d.Q6J("clearButton", !1)("formControl", ki.tubeSizeControl), d.xp6(3), d.Q6J("ngIf", ki.tubeSizeControl.hasError("required")), d.xp6(2), d.Q6J("size", "medium")("color", "blue"), d.xp6(2), d.Q6J("ngIf", ki.isLoading));
  },
  dependencies: [t.O5, T._Y, T.Fj, T.JJ, T.JL, T.F, T.oH, fe.z, We.m, st.l, ye.g, ae.l, Y.q, Re.R, G.HY, te.L, pe.H, be.Bf, le.mc, q.$, mt.R, n.J, Se.e],
  styles: ["[_nghost-%COMP%]{display:block;width:100%;height:100%}@media (max-width: 960px){[_nghost-%COMP%]     .lu-modal.dialog{padding:24px 16px 16px}}@media (max-width: 960px){[_nghost-%COMP%]     .lu-modal-header-title{font-size:17px;line-height:24px}}@media (max-width: 960px){.add-patient[_ngcontent-%COMP%]{display:flex;flex-direction:column;height:100%}}@media (min-width: 992px){.add-patient[_ngcontent-%COMP%]{width:528px}}.add-patient[_ngcontent-%COMP%]   .form__group--dept[_ngcontent-%COMP%]     lu-input-wrapper[data-lu-input-disabled=true] .lu-floated-content lu-combobox-controls lu-clear-control{display:none}.add-patient[_ngcontent-%COMP%]   .wrap[_ngcontent-%COMP%]{display:flex;align-items:flex-start;gap:16px}.add-patient[_ngcontent-%COMP%]   .date[_ngcontent-%COMP%]     lu-calendar-field-host{--lu-input-width: 136px}.add-patient[_ngcontent-%COMP%]   .time[_ngcontent-%COMP%]{max-width:112px}.add-patient[_ngcontent-%COMP%]   .time[_ngcontent-%COMP%]   .form__group-label[_ngcontent-%COMP%]{opacity:0}.add-patient[_ngcontent-%COMP%]   .tube[_ngcontent-%COMP%]{width:248px}@media (max-width: 960px){.add-patient[_ngcontent-%COMP%]   .tube[_ngcontent-%COMP%]{flex-grow:1}}.add-patient[_ngcontent-%COMP%]   .btn-wrapper[_ngcontent-%COMP%]     .lu-button-wrapper{width:111px}@media (max-width: 960px){.add-patient[_ngcontent-%COMP%]   .btn-wrapper[_ngcontent-%COMP%]{margin-top:auto}}"],
  changeDetection: 0
});
