// Exact compiled component metadata; references belong to modules/42437.js
({
  type: Fi,
  selectors: [["app-add-patient-modal"]],
  decls: 65,
  vars: 25,
  consts: [["class", "loader-wrapper", 4, "ngIf"], [1, "form__group"], [1, "form__group-label"], ["lu-label", ""], [3, "formControl"], ["type", "error", 4, "ngIf"], ["type", "autocomplete", 3, "formControl", "displayValueFn", "inputChange", "beforeClose"], ["comboboxFio", ""], [3, "items", "itemContent", "showPreloader", "emptyContent", 4, "luData"], [1, "wrap"], [3, "formControl", "minDate", "maxDate"], [1, "form__group", "form__group--time"], ["type", "text", "luInput", "", "luInputString", "", "luMask", "HH:MM", "placeholder", "ЧЧ:ММ", "autocomplete", "off", 3, "formControl"], ["type", "error", "class", "modal_error", 4, "ngIf"], ["type", "autocomplete", 3, "clearButton", "formControl", "displayValueFn"], ["combobox", ""], [3, "items", "itemContent", 4, "luData"], [1, "form__group", "form__group--stoma-name"], [4, "ngIf"], ["luInput", "", "luInputString", "", 3, "formControl"], [1, "form__group", "form__group--size"], ["luInput", "", "luInputString", "", 3, "value", "input"], ["class", "form__group", 4, "ngIf"], [1, "btn-wrapper"], ["lu-button-raised", "", 3, "size", "color", "click"], [1, "loader-wrapper"], [1, "loader"], ["type", "error"], ["icon", "warning", 3, "size"], [3, "items", "itemContent", "showPreloader", "emptyContent"], ["loadingTemplate", ""], ["patientTemplate", ""], ["size", "inline-dropdown"], [3, "innerHTML"], ["type", "error", 1, "modal_error"], [3, "items", "itemContent"], ["stomaTypeTemplate", ""], ["type", "autocomplete", 3, "formControl", "displayValueFn"], ["comboboxDoc", ""], ["doctorTemplate", ""]],
  template: function (Oi, Ji) {
    1 & Oi && (e.YNc(0, Pi, 2, 0, "div", 0), e.TgZ(1, "form")(2, "div", 1)(3, "span", 2), e._uU(4, "Отделение "), e.TgZ(5, "span"), e._uU(6, "*"), e.qZA()(), e.TgZ(7, "label", 3), e._UZ(8, "hl-department-combobox", 4), e.YNc(9, Ii, 3, 1, "lu-form-message", 5), e.qZA()(), e.TgZ(10, "div", 1)(11, "span", 2), e._uU(12, "ФИО пациента "), e.TgZ(13, "span"), e._uU(14, "*"), e.qZA()(), e.TgZ(15, "label", 3)(16, "lu-combobox", 6, 7), e.NdJ("inputChange", function (Sr) {
      return Ji.onPatientSearchTextChange(Sr);
    })("beforeClose", function () {
      return Ji.onPatientComboboxBeforeClose();
    }), e.YNc(18, fr, 6, 7, "lu-data-list", 8), e.qZA(), e.YNc(19, pt, 3, 1, "lu-form-message", 5), e.YNc(20, Dt, 3, 1, "lu-form-message", 5), e.qZA()(), e.TgZ(21, "div")(22, "span", 2), e._uU(23, "Начало ухода "), e.TgZ(24, "span"), e._uU(25, "*"), e.qZA()(), e.TgZ(26, "div", 9)(27, "div", 1)(28, "label", 3), e._UZ(29, "lu-calendar-field", 10), e.YNc(30, Ht, 3, 1, "lu-form-message", 5), e.qZA()(), e.TgZ(31, "div", 11)(32, "label", 3)(33, "lu-input-wrapper"), e._UZ(34, "input", 12), e.YNc(35, Dn, 3, 1, "lu-form-message", 13), e.YNc(36, vt, 3, 1, "lu-form-message", 13), e.qZA()()()()(), e.TgZ(37, "div", 1)(38, "span", 2), e._uU(39, "Вид стомы "), e.TgZ(40, "span"), e._uU(41, "*"), e.qZA()(), e.TgZ(42, "label", 3)(43, "lu-combobox", 14, 15), e.YNc(45, li, 4, 5, "lu-data-list", 16), e.qZA(), e.YNc(46, zn, 3, 1, "lu-form-message", 5), e.qZA()(), e.TgZ(47, "div", 9)(48, "div", 17)(49, "span", 2), e._uU(50, "Название "), e.YNc(51, $t, 2, 0, "span", 18), e.qZA(), e.TgZ(52, "label", 3)(53, "lu-input-wrapper"), e._UZ(54, "input", 19), e.qZA(), e.YNc(55, Mn, 3, 1, "lu-form-message", 5), e.qZA()(), e.TgZ(56, "div", 20)(57, "span", 2), e._uU(58, "Размер"), e.qZA(), e.TgZ(59, "lu-input-wrapper")(60, "input", 21), e.NdJ("input", function (Sr) {
      return Ji.changeStomaSize(Sr);
    }), e.qZA()()()(), e.YNc(61, To, 10, 3, "div", 22), e.TgZ(62, "div", 23)(63, "button", 24), e.NdJ("click", function () {
      return Ji.onSubmit();
    }), e._uU(64, "Добавить"), e.qZA()()()), 2 & Oi && (e.Q6J("ngIf", Ji.isLoad), e.xp6(8), e.Q6J("formControl", Ji.deptControl), e.xp6(1), e.Q6J("ngIf", Ji.deptControl.hasError("required")), e.xp6(7), e.Q6J("formControl", Ji.patientControl)("displayValueFn", Ji.displayPatientt.bind(Ji)), e.xp6(3), e.Q6J("ngIf", Ji.patientControl.touched && !Ji.selectedPatient), e.xp6(1), e.Q6J("ngIf", Ji.patientControl.touched && Ji.patientControl.hasError("missingIdentifiers")), e.xp6(9), e.Q6J("formControl", Ji.dateControl)("minDate", Ji.minDate)("maxDate", Ji.maxDate), e.xp6(1), e.Q6J("ngIf", Ji.dateControl.touched && Ji.dateControl.hasError("required")), e.xp6(4), e.Q6J("formControl", Ji.timeControl), e.xp6(1), e.Q6J("ngIf", Ji.timeControl.touched && Ji.timeControl.hasError("invalidTime")), e.xp6(1), e.Q6J("ngIf", Ji.timeControl.touched && Ji.timeControl.hasError("required")), e.xp6(7), e.Q6J("clearButton", !1)("formControl", Ji.stomaTypeControl)("displayValueFn", Ji.displayStomaKind), e.xp6(3), e.Q6J("ngIf", Ji.stomaTypeControl.touched && Ji.stomaTypeControl.hasError("required")), e.xp6(5), e.Q6J("ngIf", "Иное" === (null == Ji.stomaTypeControl.value ? null : Ji.stomaTypeControl.value.display)), e.xp6(3), e.Q6J("formControl", Ji.stomaNameControl), e.xp6(1), e.Q6J("ngIf", Ji.stomaNameControl.hasError("required")), e.xp6(5), e.Q6J("value", Ji.stomaSize), e.xp6(1), e.Q6J("ngIf", Ji.isShowDoctorAgreementField), e.xp6(2), e.Q6J("size", "medium")("color", "blue"));
  },
  dependencies: [st.O5, a._Y, a.Fj, a.JJ, a.JL, a.F, a.oH, q.z, Mt.m, Xt.l, mt.g, ut.l, Ct.q, Je.R, Ft.HY, Et.L, Ue.H, Me.Bf, Ke.mc, Nn.Js, Ze.d, st.uU, Ee.J, je.e],
  styles: ["[_nghost-%COMP%]{display:block;width:528px}.form__group--time[_ngcontent-%COMP%], .form__group--size[_ngcontent-%COMP%]{max-width:112px}.wrap[_ngcontent-%COMP%]{display:flex;gap:16px}.wrap[_ngcontent-%COMP%]   .form__group--time[_ngcontent-%COMP%]   .form__group-label[_ngcontent-%COMP%]{opacity:0;visibility:hidden}.wrap[_ngcontent-%COMP%]   label[data-lu-control-state=error][_ngcontent-%COMP%]{padding-bottom:24px}.wrap[_ngcontent-%COMP%]   lu-form-message[_ngcontent-%COMP%]{width:max-content}.modal_error[_ngcontent-%COMP%]{margin-top:var(--lu-base-gutter)}.form__group--stoma-name[_ngcontent-%COMP%]{flex-grow:1}  .form__group lu-calendar-field lu-calendar-field-host{--lu-input-width: 136px !important}@media (max-width: 960px){.btn-wrapper[_ngcontent-%COMP%]{position:fixed;bottom:0;right:0;padding:16px;background-color:#fff;z-index:100}}.loader-wrapper[_ngcontent-%COMP%]{position:absolute;top:0;left:0;display:flex;align-items:center;justify-content:center;width:100%;height:100%;background-color:rgba(var(--lu-black-rgb-100),.5);z-index:100}.loader[_ngcontent-%COMP%]{width:48px;height:48px;border:5px solid #fff;border-bottom-color:transparent;border-radius:50%;display:inline-block;box-sizing:border-box;animation:_ngcontent-%COMP%_rotation 1s linear infinite}@keyframes _ngcontent-%COMP%_rotation{0%{transform:rotate(0)}to{transform:rotate(360deg)}}"]
});
