// Exact compiled component metadata; references belong to modules/42437.js
({
  type: Rn,
  selectors: [["app-add-stoma-modal"]],
  decls: 38,
  vars: 14,
  consts: [["class", "loader-wrapper", 4, "ngIf"], [1, "form__group", "form__group--time"], [1, "form__group-label"], ["lu-label", ""], ["luInput", "", "luInputString", "", "luMask", "HH:MM", 3, "formControl"], ["type", "error", 4, "ngIf"], [1, "form__group"], ["type", "autocomplete", 3, "clearButton", "formControl", "displayValueFn"], ["combobox_stomaType", ""], [3, "items", "itemContent", 4, "luData"], [1, "wrap"], [1, "form__group", "form__group--stoma-name"], [4, "ngIf"], ["luInput", "", "luInputString", "", 3, "formControl"], [1, "form__group", "form__group--size"], ["luInput", "", "luInputString", "", 3, "value", "input"], ["class", "form__group", 4, "ngIf"], [1, "btn-wrapper"], ["lu-button-raised", "", 3, "size", "color", "click"], [1, "loader-wrapper"], [1, "loader"], ["type", "error"], ["icon", "warning", 3, "size"], [3, "items", "itemContent"], ["itemContent_stomaType", ""], [3, "innerHTML"], ["type", "autocomplete", 3, "formControl", "displayValueFn"], ["combobox", ""], ["itemContent", ""]],
  template: function (Oi, Ji) {
    1 & Oi && (e.YNc(0, Yi, 2, 0, "div", 0), e.TgZ(1, "div", 1)(2, "span", 2), e._uU(3, "Время "), e.TgZ(4, "span"), e._uU(5, "*"), e.qZA()(), e.TgZ(6, "label", 3)(7, "lu-input-wrapper"), e._UZ(8, "input", 4), e.qZA(), e.YNc(9, Eo, 3, 1, "lu-form-message", 5), e.qZA()(), e.TgZ(10, "div", 6)(11, "span", 2), e._uU(12, "Вид стомы "), e.TgZ(13, "span"), e._uU(14, "*"), e.qZA()(), e.TgZ(15, "label", 3)(16, "lu-combobox", 7, 8), e.YNc(18, br, 4, 5, "lu-data-list", 9), e.qZA(), e.YNc(19, Pr, 3, 1, "lu-form-message", 5), e.qZA()(), e.TgZ(20, "div", 10)(21, "div", 11)(22, "span", 2), e._uU(23, "Название "), e.YNc(24, qo, 2, 0, "span", 12), e.qZA(), e.TgZ(25, "label", 3)(26, "lu-input-wrapper"), e._UZ(27, "input", 13), e.qZA(), e.YNc(28, Yo, 3, 1, "lu-form-message", 5), e.qZA()(), e.TgZ(29, "div", 14)(30, "span", 2), e._uU(31, "Размер"), e.qZA(), e.TgZ(32, "lu-input-wrapper")(33, "input", 15), e.NdJ("input", function (Sr) {
      return Ji.changeStomaSize(Sr);
    }), e.qZA()()()(), e.YNc(34, lo, 10, 3, "div", 16), e.TgZ(35, "div", 17)(36, "button", 18), e.NdJ("click", function () {
      return Ji.onSubmit();
    }), e._uU(37, "Сохранить"), e.qZA()()), 2 & Oi && (e.Q6J("ngIf", Ji.isLoad), e.xp6(8), e.Q6J("formControl", Ji.timeControl), e.xp6(1), e.Q6J("ngIf", Ji.timeControl.hasError("required")), e.xp6(7), e.Q6J("clearButton", !1)("formControl", Ji.stomaTypeControl)("displayValueFn", Ji.displayStomaType), e.xp6(3), e.Q6J("ngIf", Ji.stomaTypeControl.hasError("required")), e.xp6(5), e.Q6J("ngIf", "Иное" === (null == Ji.stomaTypeControl.value ? null : Ji.stomaTypeControl.value.display)), e.xp6(3), e.Q6J("formControl", Ji.stomaNameControl), e.xp6(1), e.Q6J("ngIf", Ji.stomaNameControl.hasError("required")), e.xp6(5), e.Q6J("value", Ji.stomaSize), e.xp6(1), e.Q6J("ngIf", Ji.isShowDoctorAgreementField), e.xp6(2), e.Q6J("size", "medium")("color", "blue"));
  },
  dependencies: [st.O5, a.Fj, a.JJ, a.oH, Ft.HY, Et.L, Ue.H, Me.Bf, Mt.m, Xt.l, mt.g, q.z, ut.l, Ct.q, Ke.mc, Ee.J, je.e],
  styles: ["[_nghost-%COMP%]{display:block;width:528px}.form__group--time[_ngcontent-%COMP%]   lu-input-wrapper[_ngcontent-%COMP%], .form__group--size[_ngcontent-%COMP%]{max-width:112px}.wrap[_ngcontent-%COMP%]{display:flex;gap:16px}.form__group--stoma-name[_ngcontent-%COMP%]{flex-grow:1}@media (max-width: 960px){[_nghost-%COMP%]{width:100%!important}.btn-wrapper[_ngcontent-%COMP%]{position:fixed;bottom:0;right:0;padding:16px;background-color:#fff;z-index:100}}.loader-wrapper[_ngcontent-%COMP%]{position:absolute;top:0;left:0;display:flex;align-items:center;justify-content:center;width:100%;height:100%;background-color:rgba(var(--lu-black-rgb-100),.5);z-index:100}.loader[_ngcontent-%COMP%]{width:48px;height:48px;border:5px solid #fff;border-bottom-color:transparent;border-radius:50%;display:inline-block;box-sizing:border-box;animation:_ngcontent-%COMP%_rotation 1s linear infinite}@keyframes _ngcontent-%COMP%_rotation{0%{transform:rotate(0)}to{transform:rotate(360deg)}}"]
});
