// Exact compiled component metadata; references belong to modules/44785.js
({
  type: Sf,
  selectors: [["app-dispensing-confirmation-modal"]],
  standalone: !0,
  features: [n.jDz],
  decls: 21,
  vars: 7,
  consts: [[1, "dispensing-modal"], [1, "dispensing-modal__header"], [1, "dispensing-modal__title"], ["aria-label", "Закрыть", 1, "dispensing-modal__close", 3, "click"], ["icon", "close", 3, "size"], [1, "dispensing-modal__body"], [1, "dispensing-modal__info"], [1, "dispensing-modal__info-row"], [1, "dispensing-modal__label"], [1, "dispensing-modal__value"], ["class", "dispensing-modal__warning", 4, "ngIf"], ["class", "dispensing-modal__message", 4, "ngIf"], ["class", "dispensing-modal__actions", 4, "ngIf"], [1, "dispensing-modal__warning"], ["icon", "warning", 1, "dispensing-modal__warning-icon", 3, "size"], [1, "dispensing-modal__message"], [1, "dispensing-modal__actions"], ["lu-button-outer", "", 3, "size", "color", "click"], ["lu-button-raised", "", 3, "size", "color", "click"]],
  template: function (k, ce) {
    1 & k && (n.TgZ(0, "div", 0)(1, "div", 1)(2, "h2", 2), n._uU(3), n.qZA(), n.TgZ(4, "button", 3), n.NdJ("click", function () {
      return ce.onCancel();
    }), n._UZ(5, "lu-svg-icon", 4), n.qZA()(), n.TgZ(6, "div", 5)(7, "div", 6)(8, "p", 7)(9, "span", 8), n._uU(10, "Пациент:"), n.qZA(), n.TgZ(11, "span", 9), n._uU(12), n.qZA()(), n.TgZ(13, "p", 7)(14, "span", 8), n._uU(15, "Препарат:"), n.qZA(), n.TgZ(16, "span", 9), n._uU(17), n.qZA()()(), n.YNc(18, ca, 4, 2, "div", 10), n.YNc(19, _a, 2, 1, "p", 11), n.YNc(20, wl, 5, 4, "div", 12), n.qZA()()), 2 & k && (n.xp6(3), n.Oqu(ce.title), n.xp6(2), n.Q6J("size", 24), n.xp6(7), n.Oqu(ce.data.patientName), n.xp6(5), n.Oqu(ce.medicationName), n.xp6(1), n.Q6J("ngIf", ce.isInfoMode), n.xp6(1), n.Q6J("ngIf", !ce.isInfoMode), n.xp6(1), n.Q6J("ngIf", !ce.isInfoMode));
  },
  dependencies: [Di.ez, Di.O5, Ks.W1, Ks.mc, Ci.h, Ci.q],
  styles: [".dispensing-modal[_ngcontent-%COMP%]{background:#fff;border-radius:4px;box-shadow:0 4px 24px #00000026;width:576px;min-height:280px;padding:24px;display:flex;flex-direction:column;gap:24px}.dispensing-modal__header[_ngcontent-%COMP%]{display:flex;align-items:flex-start;justify-content:space-between}.dispensing-modal__title[_ngcontent-%COMP%]{margin:0;font-family:Open Sans,sans-serif;font-weight:600;font-size:20px;line-height:28px;letter-spacing:0;color:#333;padding-right:16px}.dispensing-modal__close[_ngcontent-%COMP%]{background:none;border:none;cursor:pointer;padding:0;flex-shrink:0;--lu-svg-icon-color: #ccc}.dispensing-modal__close[_ngcontent-%COMP%]:hover{--lu-svg-icon-color: #757575}.dispensing-modal__body[_ngcontent-%COMP%]{display:flex;flex-direction:column;gap:16px;flex:1}@media (min-width: 961px){.dispensing-modal__info[_ngcontent-%COMP%]{display:flex;flex-direction:column;gap:8px}}.dispensing-modal__info-row[_ngcontent-%COMP%]{margin:0;font-size:15px;line-height:24px}.dispensing-modal__label[_ngcontent-%COMP%]{font-weight:600;color:#333;margin-right:4px}.dispensing-modal__value[_ngcontent-%COMP%]{color:#333}.dispensing-modal__message[_ngcontent-%COMP%]{margin:0;font-size:15px;line-height:24px;color:#333}.dispensing-modal__warning[_ngcontent-%COMP%]{display:flex;align-items:flex-start;gap:8px;padding:12px;background-color:#ffefd3;border-radius:4px;font-size:13px;line-height:20px;color:#333}.dispensing-modal__warning-icon[_ngcontent-%COMP%]{flex-shrink:0;color:#f9a825;margin-top:2px;--lu-svg-icon-color: #ccc}.dispensing-modal__actions[_ngcontent-%COMP%]{display:flex;justify-content:flex-end;gap:16px;margin-top:auto}"]
});
